### PR TITLE
Factor out CLI parsing into a separate file/module

### PR DESCRIPTION
**Pull request by JakeOShannessy**
This patch which contains a new CLI parser. This does two important things:

* Disallows the CLI parser from modifying any global variables or otherwise affecting any other parts of the code. This is a first step small step towards reducing the number of global variables.
* Serializes all possible options to a struct which can be documented and type checked.

This might seem like an unimportant reorganisation but will make it easier to do things in the future (next step being clarification of CHID vs filename etc.). This also adds some additional bounds checks.

### CODE REVIEW

**Comment by gforney** [comment]
I'm getting a lot of warning when building smokeview.  can be fixed by including option.h or options_common.h at the top of command_args.c . I'll let you do this - I dont know if there are any side effects which might cause other problems. . I use options.h to set preprocessing directives which turn on or off various features I am testing. .  options_comon.h sets some directives that will eliminate the warnings.

I'm taking off next week so won't be able to look at this more until the week after next

**Comment by JakeOShannessy** [comment]
Thanks Glenn, I've made that change. I assume you're referring to the warnings Intel gives on Windows. I'm not seeing them locally but they may still be occurring on the Github Actions build (https://github.com/firemodels/smv/actions/runs/5164024517/jobs/9302679518). Could you give the update a try?

**Comment by gforney** [comment]
Im out of town without access to a computer. Ill give it a try when i get
back. I was getting warnings about various c routines being deprecated.  I
set the preprocessing directive to make these warnings go away in
options_common.h .

**Comment by gforney** [comment]
I'm testing your PR using smokebot our smokeview verification script.

i'm getting these errors/warnings when compiling using make_smokeview_db.sh in smv/Build/gnu_linux_64 .  

../../../Source//smokeview/command_args.c: In function ‘ParseCommandlineNew’:
../../../Source//smokeview/command_args.c:39:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 1; i < argc; i++) {
   ^
../../../Source//smokeview/command_args.c:39:3: note: use option -std=c99 or -std=gnu99 to compile your code
   ^

gcc -c -O0 -m64 -ggdb -Wall -Wno-parentheses -Wno-unknown-pragmas -Wno-comment -Wno-write-strings           -D pp_LINUX -D pp_GCC -D pp_NOQUARTZ -Dpp_C                                                                                                OMPVER=\""gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)"\" -Dpp_GITHASH=\"SMV-6.8.0-175-gf26189454-test_1599\" -Dpp_GITDATE=\""Sat Jun 3 14:55:56 2023 +0                                                                                                100\""   -I ../../../Source//glui_v2_1_beta -I ../../../Source//gd-2.0.15 -I ../../../Source//shared -I ../../../Source//smokeview -I ../../../Source//                                                                                                glew -I ../../../Source//zlib128 ../../../Source//smokeview/main.c
../../../Source//smokeview/main.c: In function ‘ProcessCommandLine’:
../../../Source//smokeview/main.c:102:7: warning: unused variable ‘iarg’ [-Wunused-variable]
   int iarg;

**Comment by gforney** [comment]
I fixed the above errors/warnings in PR #1606 .  I could probably also add std=c99 to linux and windows targets (making some of the fixes unnecessary) since it is already there for osx targets.  I'll wait to do this for a future PR to make sure there are no problems or unintended side effects

**Comment by JakeOShannessy** [comment]
Thanks Glenn. I had noted that c99 was set (at least in some cases) so was coding to that. I'm surprised it didn't throw up more errors.

A c99 flag (or even a c89 flag if that was preferred) might be useful as my gcc setup isn't currently showing me that warning. Theoretically a standards flag should help us see the same warnings.

**Pull request merged**
