### PR TITLE
Modify parse_smv_benchmark to include some basic JSON output

### PR DESCRIPTION
**Pull request by JakeOShannessy**
This PR makes a slight tweak to ReadSMV to split it into three stages, with the aim of simplifying it.

Mainly this modifies `parse_smv_benchmark.c` to output some JSON for testing. This also serves as an example of how separating ReadSMV could allow it to be used to make simple queries of a *.smv file (for example, meshes dimensions).

### CODE REVIEW

**Comment by JakeOShannessy** [comment]
e.g.
```bash
parse_smv_benchmark ./Verification/Visualization/thouse5.smv | jq .title
```
```json
"Town House Kitchen Fire"
```
e.g.
```bash
parse_smv_benchmark ./Verification/Visualization/thouse5.smv | jq .meshes
```
```json
[
  {
    "index": 1,
    "id": "MESH_0000001",
    "coordinates": {
      "i": 24,
      "j": 20,
      "k": 24
    },
    "dimensions": {
      "x_min": 0.0,
      "x_max": 0.80000001192092896,
      "y_min": 0.0,
      "y_ax": 0.5,
      "z_min": 0.0,
      "z_max": 0.60000002384185791
    }
  },
  {
    "index": 2,
    "id": "MESH_0000002",
    "coordinates": {
      "i": 24,
      "j": 20,
      "k": 24
    },
    "dimensions": {
      "x_min": 0.0,
      "x_max": 0.80000001192092896,
      "y_min": 0.5,
      "y_ax": 1.0,
      "z_min": 0.0,
      "z_max": 0.60000002384185791
    }
  }
]
```

**Comment by gforney** [comment]
1.  don't see where nmeshes is defined'

2.  got these warnings when I built with gnu_linux_64_db target
../../../Source//smokeview/readsmv.c:6874:9: warning: declaration of ‘processing_time’ shadows a global declaration [-Wshadow]
 6874 |   float processing_time, wrapup_time, getfilelist_time;
      |         ^~~~~~~~~~~~~~~
../../../Source//smokeview/readsmv.c:6579:14: note: shadowed declaration is here
 6579 | static float processing_time;
      |              ^~~~~~~~~~~~~~~
../../../Source//smokeview/readsmv.c:6874:39: warning: declaration of ‘getfilelist_time’ shadows a global declaration [-Wshadow]
 6874 |   float processing_time, wrapup_time, getfilelist_time;
      |                                       ^~~~~~~~~~~~~~~~
../../../Source//smokeview/readsmv.c:6580:14: note: shadowed declaration is here
 6580 | static float getfilelist_time;
      |              ^~~~~~~~~~~~~~~~
../../../Source//smokeview/readsmv.c:6874:39: warning: unused variable ‘getfilelist_time’ [-Wunused-variable]
 6874 |   float processing_time, wrapup_time, getfilelist_time;
      |                                       ^~~~~~~~~~~~~~~~
../../../Source//smokeview/readsmv.c:6874:26: warning: unused variable ‘wrapup_time’ [-Wunused-variable]
 6874 |   float processing_time, wrapup_time, getfilelist_time;
      |                          ^~~~~~~~~~~
../../../Source//smokeview/readsmv.c:6874:9: warning: unused variable ‘processing_time’ [-Wunused-variable]
 6874 |   float processing_time, wrapup_time, getfilelist_time;

**Comment by gforney** [comment]
minor comment - I add a comment before each routine giving routine name - to make it easier to see where new routines start

**Comment by gforney** [comment]
don't think nsurfinfo should be set to 1, should be set to 0

**Comment by JakeOShannessy** [comment]
> don't think nsurfinfo should be set to 1, should be set to 0

I thought this had come from somewhere else, I've changed it back in the rebase.

**Comment by JakeOShannessy** [comment]
> minor comment - I add a comment before each routine giving routine name - to make it easier to see where new routines start

I've added both the header lines as used elsewhere and Doxygen comments (as per FDS). Doxygen comments are a godsend in an IDE.

**Comment by JakeOShannessy** [comment]
> 1. don't see where nmeshes is defined' - never mind.  I see where nmeshes is defined now
> 
>     2. got these warnings when I built with gnu_linux_64_db target
>        ../../../Source//smokeview/readsmv.c:6874:9: warning: declaration of ‘processing_time’ shadows a global declaration [-Wshadow]
>        6874 |   float processing_time, wrapup_time, getfilelist_time;
>        |         ^~~~~~~~~~~~~~~
>        ../../../Source//smokeview/readsmv.c:6579:14: note: shadowed declaration is here
>        6579 | static float processing_time;
>        |              ^~~~~~~~~~~~~~~
>        ../../../Source//smokeview/readsmv.c:6874:39: warning: declaration of ‘getfilelist_time’ shadows a global declaration [-Wshadow]
>        6874 |   float processing_time, wrapup_time, getfilelist_time;
>        |                                       ^~~~~~~~~~~~~~~~
>        ../../../Source//smokeview/readsmv.c:6580:14: note: shadowed declaration is here
>        6580 | static float getfilelist_time;
>        |              ^~~~~~~~~~~~~~~~
>        ../../../Source//smokeview/readsmv.c:6874:39: warning: unused variable ‘getfilelist_time’ [-Wunused-variable]
>        6874 |   float processing_time, wrapup_time, getfilelist_time;
>        |                                       ^~~~~~~~~~~~~~~~
>        ../../../Source//smokeview/readsmv.c:6874:26: warning: unused variable ‘wrapup_time’ [-Wunused-variable]
>        6874 |   float processing_time, wrapup_time, getfilelist_time;
>        |                          ^~~~~~~~~~~
>        ../../../Source//smokeview/readsmv.c:6874:9: warning: unused variable ‘processing_time’ [-Wunused-variable]
>        6874 |   float processing_time, wrapup_time, getfilelist_time;
These have been addressed.

**Pull request merged**
