### PR TITLE
split object functions and move to shared

### PR DESCRIPTION
**Pull request by JakeOShannessy**
There is a lot of useful code that is currently intertwined with GLUT and GLUI. This splits that code out and put it into shared.

This introduces a new head `shared_structures.h` to hold some structs which are used in shared files. This should eventually be factored out.

This is 3/7 patches that are required to parse and post-process *.smv files without GLUT/GLUI etc.

As with similar patches this doesn't change functionality, with the exception that the global `sv_object` variables are combined into a single `object_collection` struct.

### CODE REVIEW

**Comment by gforney** [comment]
jake, smokeview -runscript hvac_comp is crashing.  to fix
in glui_tour.cpp in line 357 change
 LISTBOX_avatar->set_int_val(glui_avatar_index);
to
 if(LISTBOX_avatar!=NULL)LISTBOX_avatar->set_int_val(glui_avatar_index);

also, the texture is not being applied to the sphere in the objects_dynamics case.  I'm investigating

**Comment by JakeOShannessy** [comment]
I think there is an issue with the way I'm running the test cases that these didn't crop up, so I'm going to review that. I've managed to reproduce the first one now.

**Comment by JakeOShannessy** [comment]
I've found the issues and will update accordingly.

**Comment by gforney** [comment]
thanks.  also take a look at the levelset2 case in smv/Verification/WUI directory. smokebot running with this PR found only two cases with differences.  the sphere case mentioned earlier and the levelset2 case.  

levelset2_diffs

**Comment by gforney** [comment]
i was not able to reproduce the problem with the levelset2 case running smokeview with this PR on windows.  push up your changes when you are ready and I'll look at it again

**Comment by gforney** [comment]
I found the problem with the texture sphere in smv/Verification/Visualization/objects_dynamic.fds .  The UpdateDeviceTextures routine in getobjects.c computed some values that were global variables - they needed to be returned to the calling routine.  my changes are in the branch test_1952 which is your PR + my commit to fix this .  let me know if something else would be easier to obtain my changes
https://github.com/gforney/smv/tree/test_1952

**Comment by JakeOShannessy** [comment]
I've merged your commit to this PR.

**Pull request merged**
