### PR TITLE
Add arbitrary information to title box including CHID

### PR DESCRIPTION
**Pull request by JakeOShannessy**
This PR depends on #122. 

This PR abstracts the adding of lines of information to the title box (where currently version information is displayed). Using this abstraction a line for CHID is added, along with the GUI, .ini, and Lua controls options for it.

This  also allows for arbitrary information to be added via Lua scripts. The title box holds two kinds of text data, those hardcoded in the program (such as those that already exist) and those added dynamically.

An example of information added dynamically is shown in the script below:

```lua
initsmvdata()
print(chid)
print(fdsprefix)

add_title_line(string.format("Date: %s", os.date("%c")))
add_title_line(string.format("CHID Again: %s", chid))

-- calculate the total number of cells
local total_cells = 0
for i,mesh in pairs(meshinfo) do
    local cells = mesh.ibar * mesh.jbar * mesh.kbar
    total_cells = total_cells + cells
end

add_title_line(string.format("No. Cells: %d over  %d meshes", total_cells, nmeshes))

yieldscript()
```

The results of this script can be seen in this rendering:

titletextexample

I would like to make a change in behaviour so that we can only see whichever pieces of information we like, currently the Smokeview label is compulsory, but that will change behaviour for everybody, so I've kept that separate.

I'm not sure how it should be named, or where to best locate the code, so I've started like this. This is just a draft, but it maintains the current behaviour. Margins and font sizes may need clarification, but that existed before these changes also.

### CODE REVIEW

**Comment by gforney** [comment]
Jake,
looks good.  before I accept it can you change calls to allocate and free memory to use NewMemory and FREEMEMORY (see examples elsewhere in the code).  You will also need to include MALLOC.h in any routine that uses these NewMemory or FREEMEMORY.  I wrote a set of routines (based upon a reference I can't find now) that sit on top of malloc and free that add some rudimentary error checking.  Besides memory that is requested, NewMemory allocates an extra block of memory it uses to store a "guard" byte with a known value.  I also store the name of the routine and location where the allocation occurred..  When smokeview runs in debug mode, and whenever any memory allocation/free operation is performed, all memory blocks are checked to ensure this "guard" byte is correct.  If it is not , I assume that a memory overwrite has occurred and I cause smokview to crash.  This feature has saved me many times!  I also have a CheckMemory directive I sprinkle throughout the code to force a checks of memory blocks.  This checking does not occur in release mode so does not affect performance.  (don't really notice any performance issues in debug mode iether).

Looks like you did it correctly but we'll have to be care about screen space adding the extra title lines.

Let me know if you have any questions.

**Comment by gforney** [comment]
another comment.  I may not be perfectly consistent but one coding convention I try to follow is to use xxxxdata for a structure definition and xxxxinfo for the variable name for that structure (ie can you pick a different name for your variable titledata).  Also, I know I use too many global variables but I try to keep global and local variable names different.  If I had it to over again I would add some prefix to a global variable name to hilight the fact that they are global.  Anyway, when I compiled infoheader.c I get the following warnings.  Could you change the variable names so that they don't clash with global variable names.
thanks,
glenn

1>------ Build started: Project: smokeview, Configuration: Beta Debug x64 ------
1>  infoheader.c
1>..\..\FireModels_fork\smv\Source\smokeview\infoheader.c(15): message #3280: declaration hides variable "titledata" (declared at line 11)
1>    int addTitleLine(infoboxdata *titledata, const char *string) {
1>                                  ^
1>
1>..\..\FireModels_fork\smv\Source\smokeview\infoheader.c(38): message #3280: declaration hides variable "titledata" (declared at line 11)
1>    int clearTitleLines(infoboxdata *titledata) {
1>                                     ^
1>
1>..\..\FireModels_fork\smv\Source\smokeview\infoheader.c(49): message #3280: declaration hides variable "titledata" (declared at line 11)
1>    int initialiseInfoHeader(infoboxdata *titledata,
1>                                          ^
1>
1>..\..\FireModels_fork\smv\Source\smokeview\infoheader.c(50): message #3280: declaration hides variable "release_title" (declared at line 993 of "C:\Users\gforney\FireModels_fork\smv\Source\smokeview\smokeviewvars.h")
1>                             char *release_title, char *smv_githash,
1>                                   ^
1>
1>..\..\FireModels_fork\smv\Source\smokeview\infoheader.c(50): message #3280: declaration hides variable "smv_githash" (declared at line 850 of "C:\Users\gforney\FireModels_fork\smv\Source\smokeview\smokeviewvars.h")
1>                             char *release_title, char *smv_githash,
1>                                                        ^
1>
1>..\..\FireModels_fork\smv\Source\smokeview\infoheader.c(51): message #3280: declaration hides variable "fds_githash" (declared at line 849 of "C:\Users\gforney\FireModels_fork\smv\Source\smokeview\smokeviewvars.h")
1>                             char *fds_githash, char *chidfilebase) {
1>                                   ^
1>
1>..\..\FireModels_fork\smv\Source\smokeview\infoheader.c(51): message #3280: declaration hides variable "chidfilebase" (declared at line 1133 of "C:\Users\gforney\FireModels_fork\smv\Source\smokeview\smokeviewvars.h")
1>                             char *fds_githash, char *chidfilebase) {
1>                                                      ^
1>
1>..\..\FireModels_fork\smv\Source\smokeview\infoheader.c(76): message #3280: declaration hides variable "VP_title" (declared at line 241 of "C:\Users\gforney\FireModels_fork\smv\Source\smokeview\smokeviewvars.h")
1>    int renderInfoHeader(portdata *VP_title, infoboxdata *titledata) {
1>                                   ^
1>
1>..\..\FireModels_fork\smv\Source\smokeview\infoheader.c(76): message #3280: declaration hides variable "titledata" (declared at line 11)
1>    int renderInfoHeader(portdata *VP_title, infoboxdata *titledata) {
1>                                                          ^
1>
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by JakeOShannessy** [comment]
Thanks Glenn.

I updated the memory allocations to use those macros, looks like an handy feature to have.

I've updated the variable and type names to fit the naming scheme, I was a bit unsure, hopefully this update will suffice. To avoid shadowing the global names in the initialisation function I've appended `_string` to make it clear it is a string representing that information and to differentiate it from the globals. I've also appended `_ptr` to the `titleinfo` for the same reason. I don't know if that was the cleanest way to do it, but I'm striving to avoid globals where I can. Let me know if you have any input. 

I've removed `VP_title` out of the parameters and left it global. It's used globally already anyway, so it's still fairly simple, and still keeps use of globals in those new functions low.

**Comment by gforney** [comment]
fyi:  I wrote a routine called PRINTF which behaves like printf normally but when smokeview runs a smokeview script PRINTF redirects output to a log file.  I changed several instances of fprintf(stderr in infoheader.c to PRINTF so that extraneous output does not go to the screen when running a script.

**Pull request merged**
